//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class PJ_PROJECT
    {
        public PJ_PROJECT()
        {
            this.PJ_PROJECT1 = new HashSet<PJ_PROJECT>();
            this.PJ_PROJECT11 = new HashSet<PJ_PROJECT>();
        }
    
        public decimal ID { get; set; }
        public decimal OBJECT_ID { get; set; }
        public Nullable<decimal> PART_OF_OBJECT_ID { get; set; }
        public decimal STATE_ID { get; set; }
        public Nullable<System.DateTime> START_DATE_FACT { get; set; }
        public Nullable<decimal> START_ID { get; set; }
        public Nullable<decimal> START_REQ_ID { get; set; }
        public Nullable<System.DateTime> END_DATE_FACT { get; set; }
        public Nullable<decimal> END_ID { get; set; }
        public Nullable<decimal> END_REQ_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public Nullable<decimal> CREATE_APPL_USER_ID { get; set; }
        public string CREATE_APPL_USER_LBL { get; set; }
        public string CREATE_SYS_USER { get; set; }
        public string CREATE_USER_HOST { get; set; }
        public string CREATE_USER_IP_ADDR { get; set; }
        public string CREATE_OS_USER { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
        public Nullable<decimal> LAST_UPDATE_APPL_USER_ID { get; set; }
        public string LAST_UPDATE_APPL_USER_LBL { get; set; }
        public string LAST_UPDATE_SYS_USER { get; set; }
        public string LAST_UPDATE_USER_HOST { get; set; }
        public string LAST_UPDATE_USER_IP_ADDR { get; set; }
        public string LAST_UPDATE_OS_USER { get; set; }
        public string LBL { get; set; }
        public Nullable<decimal> CLASS_ID { get; set; }
        public Nullable<decimal> CUST_ID { get; set; }
        public string NAME { get; set; }
        public string SHORT_NAME { get; set; }
        public Nullable<decimal> MAN_ID { get; set; }
        public string NOTE { get; set; }
        public Nullable<decimal> WORK_DAYS_FACT { get; set; }
        public Nullable<decimal> PART_OF_ID { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<decimal> STATE_CL_ID { get; set; }
        public Nullable<System.DateTime> START_DATE_PLAN { get; set; }
        public Nullable<System.DateTime> END_DATE_PLAN { get; set; }
        public Nullable<decimal> WORK_DAYS_PLAN { get; set; }
        public Nullable<decimal> HAS_CHILDREN { get; set; }
        public Nullable<decimal> DURATION_PLAN { get; set; }
        public Nullable<decimal> DURATION_FACT { get; set; }
        public Nullable<decimal> AUTHOR_ID { get; set; }
        public Nullable<System.DateTime> TASK_EXEC_LAST_DATE { get; set; }
    
        public virtual ICollection<PJ_PROJECT> PJ_PROJECT1 { get; set; }
        public virtual PJ_PROJECT PJ_PROJECT2 { get; set; }
        public virtual ICollection<PJ_PROJECT> PJ_PROJECT11 { get; set; }
        public virtual PJ_PROJECT PJ_PROJECT3 { get; set; }
    }
}
