//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class PJ_TASK_COMP
    {
        public decimal ID { get; set; }
        public decimal OBJECT_ID { get; set; }
        public Nullable<decimal> PART_OF_OBJECT_ID { get; set; }
        public decimal STATE_ID { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<decimal> START_ID { get; set; }
        public Nullable<decimal> START_REQ_ID { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<decimal> END_ID { get; set; }
        public Nullable<decimal> END_REQ_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public Nullable<decimal> CREATE_APPL_USER_ID { get; set; }
        public string CREATE_APPL_USER_LBL { get; set; }
        public string CREATE_SYS_USER { get; set; }
        public string CREATE_USER_HOST { get; set; }
        public string CREATE_USER_IP_ADDR { get; set; }
        public string CREATE_OS_USER { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
        public Nullable<decimal> LAST_UPDATE_APPL_USER_ID { get; set; }
        public string LAST_UPDATE_APPL_USER_LBL { get; set; }
        public string LAST_UPDATE_SYS_USER { get; set; }
        public string LAST_UPDATE_USER_HOST { get; set; }
        public string LAST_UPDATE_USER_IP_ADDR { get; set; }
        public string LAST_UPDATE_OS_USER { get; set; }
        public string LBL { get; set; }
        public Nullable<decimal> TASK_ID { get; set; }
        public Nullable<decimal> CLASS_ID { get; set; }
    }
}
