//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class PJ_TASK
    {
        public PJ_TASK()
        {
            this.PJ_TASK1 = new HashSet<PJ_TASK>();
            this.PJ_TASK11 = new HashSet<PJ_TASK>();
        }
    
        public decimal ID { get; set; }
        public decimal OBJECT_ID { get; set; }
        public Nullable<decimal> PART_OF_OBJECT_ID { get; set; }
        public decimal STATE_ID { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<decimal> START_ID { get; set; }
        public Nullable<decimal> START_REQ_ID { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<decimal> END_ID { get; set; }
        public Nullable<decimal> END_REQ_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public Nullable<decimal> CREATE_APPL_USER_ID { get; set; }
        public string CREATE_APPL_USER_LBL { get; set; }
        public string CREATE_SYS_USER { get; set; }
        public string CREATE_USER_HOST { get; set; }
        public string CREATE_USER_IP_ADDR { get; set; }
        public string CREATE_OS_USER { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
        public Nullable<decimal> LAST_UPDATE_APPL_USER_ID { get; set; }
        public string LAST_UPDATE_APPL_USER_LBL { get; set; }
        public string LAST_UPDATE_SYS_USER { get; set; }
        public string LAST_UPDATE_USER_HOST { get; set; }
        public string LAST_UPDATE_USER_IP_ADDR { get; set; }
        public string LAST_UPDATE_OS_USER { get; set; }
        public string LBL { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> PJ_ID { get; set; }
        public Nullable<decimal> EXEC_ID { get; set; }
        public Nullable<System.DateTime> END_DATE_PLAN { get; set; }
        public Nullable<System.DateTime> START_DATE_FACT { get; set; }
        public Nullable<System.DateTime> END_DATE_FACT { get; set; }
        public Nullable<decimal> STATE_CL_ID { get; set; }
        public Nullable<decimal> WORK_HOURS_FACT { get; set; }
        public string NOTE { get; set; }
        public Nullable<decimal> WORK_HOURS_PLAN { get; set; }
        public Nullable<decimal> PART_OF_ID { get; set; }
        public Nullable<decimal> EXEC_COMP_ID { get; set; }
        public Nullable<decimal> IS_EXEC_MANAGER { get; set; }
        public Nullable<System.DateTime> START_DATE_PLAN { get; set; }
        public Nullable<decimal> CODE { get; set; }
        public Nullable<decimal> RESOURCE_MAN_ID { get; set; }
        public Nullable<decimal> HAS_CHILDREN { get; set; }
        public Nullable<decimal> DURATION_PLAN { get; set; }
        public Nullable<decimal> DURATION_FACT { get; set; }
        public Nullable<decimal> AUTHOR_ID { get; set; }
        public Nullable<System.DateTime> ACCEPT_DATE_FACT { get; set; }
        public Nullable<System.DateTime> TASK_EXEC_LAST_DATE { get; set; }
        public string REJECT_NOTES { get; set; }
        public string CUSTOM_CODE { get; set; }
        public Nullable<decimal> ORDER_NUM { get; set; }
        public Nullable<System.DateTime> INTERRUPTION_DATE { get; set; }
        public string STATE_NOTES { get; set; }
    
        public virtual ICollection<PJ_TASK> PJ_TASK1 { get; set; }
        public virtual PJ_TASK PJ_TASK2 { get; set; }
        public virtual ICollection<PJ_TASK> PJ_TASK11 { get; set; }
        public virtual PJ_TASK PJ_TASK3 { get; set; }
    }
}
