//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.Web
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectManagerEntities : DbContext
    {
        public ProjectManagerEntities()
            : base("name=ProjectManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PJ_CLASS> PJ_CLASS { get; set; }
        public virtual DbSet<PJ_COMP> PJ_COMP { get; set; }
        public virtual DbSet<PJ_CUSTOMER> PJ_CUSTOMER { get; set; }
        public virtual DbSet<PJ_EMP> PJ_EMP { get; set; }
        public virtual DbSet<PJ_PROJECT> PJ_PROJECT { get; set; }
        public virtual DbSet<PJ_PROJECT_STATE_CL> PJ_PROJECT_STATE_CL { get; set; }
        public virtual DbSet<PJ_TASK> PJ_TASK { get; set; }
        public virtual DbSet<PJ_TASK_CLASS> PJ_TASK_CLASS { get; set; }
        public virtual DbSet<PJ_TASK_COMP> PJ_TASK_COMP { get; set; }
        public virtual DbSet<PJ_TASK_DEPENDENCY> PJ_TASK_DEPENDENCY { get; set; }
        public virtual DbSet<PJ_TASK_STATE_CL> PJ_TASK_STATE_CL { get; set; }
    }
}
